target : winexe.c winexe.h winexe_consts.h winexe_functions.h winexe_functions.c winexe_struct_filler_functions.c winexe_struct_filler_functions.h winexe_structures.h
	$(GCC) -c -o build/winexe.$(OBJECTEXT) winexe.h
